spring:
  application:
    name: kafka-message-reprocess-api

kafka:
  consumer2:
    topics: mybunnytopic
    demo:
      group-id: mygroupmac
  consumer:
    demo:
      group-id: mygroup
    demosec:
      group-id: mynewgroup
    bootstrap-servers: 192.168.0.108:9092
    topics: mydemotopic
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  seek:
    endpoints:
      enabled: true

spring-doc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html




